# Generated by Django 5.0.1 on 2024-02-04 13:36

import django.db.models.deletion
import hosting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to=hosting.models.get_video_file_name)),
                ('hash', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('discription', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
