# Generated by Django 5.0.1 on 2024-02-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='discription',
            new_name='description',
        ),
    ]
